### ISSUE TITLE
packagist

### ISSUE THREAD

**Issue by gulaandrij** [pulse-studio/xforms#4]
так как модуль готов к использованию через композер хорошей идеей будет разместить его на https://packagist.org/packages/submit

**Comment by kvalood** [comment]
Почти готов. Чуть позже обязательно выложу!
Надо кое какие мелочи поправить, и сделать валидацию полей на js. 
Так-же сейчас модуль не отправляет почту. Я пока думаю как лучше сделать(задавать парамптры smtp в настройках формы или использовать mail.php корфигурацию.)

Еще нужно доработать checkbox, сейчас по моему вообще не робит...

**Comment by gulaandrij** [comment]
почту можно отправлять через cmsemail, по примеру вишлиста

```
            $user_variables = [
                'userName' => $name,
                'userPhone' => $phone,
                'wishName' => $wish_list['title'],
                'wishLink' => site_url('wishlist/show/' . $wish_list['hash']),
                'wishListViews' => $wish_list['hash']['review_count'],
            ];

            \cmsemail\email::getInstance()->sendEmail($email, 'wish_list', $user_variables);
```

wish_list - название шаблона письма который нужно инсертить в базу модуля при инстале

```
INSERT INTO `mod_email_paterns` (`id`, `name`, `patern`, `from`, `from_email`, `admin_email`, `type`, `user_message_active`, `admin_message_active`) VALUES
(111, 'wish_list', '', 'ImageCMS Shop', 'no-replay@shop.com', '', 'HTML', 1, 1);

INSERT INTO `mod_email_paterns_i18n` (`locale`, `theme`, `user_message`, `admin_message`, `description`, `variables`) VALUES
(111, 'ru', 'Список Желаний', '<h2>Уважаемый $userName$.</h2>\n<p>Вы создали следующий список желаний $wishName$</p>\n<div>Ссылка на просмотр списка желаний -&nbsp;&nbsp; $wishLink$ <br /> Количество просмотров списка - $wishListViews$</div>', '<p>Пользователь&nbsp; $userName$ <span>создал Список Желаний -&nbsp; $wishName$ </span></p>\n<p>Ссылка на просмотр списка желаний -&nbsp;&nbsp; $wishLink$&nbsp;</p>\n<p>Количество просмотров списка - $wishListViews$</p>', '<p><span>Уведомление о создании Списка Желаний</span></p>', 'a:4:{s:10:"$userName$";s:31:"Имя пользователя";s:10:"$wishName$";s:29:"Название списка";s:10:"$wishLink$";s:30:"Ссилка на список";s:15:"$wishListViews$";s:54:"Количество просмотров списка";}');
```

**Comment by kvalood** [comment]
Вроде разместил модуль на https://packagist.org/packages/pulse-studio/xforms

cmsemail равзе не использует обычную функцию php mail?
У меня частенько хостеры обрезают отправки почты через просто mail().
Да и SMTP поинтереснее.

Может стоит сделать в настройках сайта метод отправки почты?

**Comment by gulaandrij** [comment]
![image](http://image.prntscr.com/image/1e550a8f5b194c0b85ede2a618e14015.png) такой функционал есть

**Comment by pulse-studio** [comment]
Как странно что я этого незаметил :)
Наверное стоит немного переделать модуль.

**Comment by pulse-studio** [comment]
Как отправить сообщение нескольким администраторам? 
https://cloud.mail.ru/public/LP5E/9unrfD7ns
ведь в поле "email администратора" можно ввести только 1 email
